spring:
  datasource:
    url: jdbc:postgresql://192.168.0.207:5432/postgres
    username: hjjang
    password: hjjang123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: true # systemOut log
        format_sql: true
